project 'finalproject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'finalproject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finalproject
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SVProgressHUD'
  pod "Gradients"
  pod 'PullToRefresher', '~> 3.1'
  pod 'Charts'
  pod 'TextFieldEffects'
  pod 'UIView+Shake'
  pod 'DropDown'
  pod 'NotificationBannerSwift'
  pod "BWWalkthrough"
  pod "CDAlertView"
  pod 'TransitionButton'
  pod 'PMSuperButton'
  pod "Pastel"
  pod "Floaty", "~> 4.1.0"
  pod 'SwiftyBeaver'
end
